感染症病床使用率カードが翻訳されるように修正
nomunomu0504/covid19 pull request #7953
Opened 2021-05-23 14:05 UTC by stshsn

## 👏 解決する issue / Resolved Issues
- close #7519 

## ⛏ 変更内容 / Details of Changes

- 感染症病床使用率カードが英語に翻訳されるように修正
- その他の英語アセットを修正

## 📸 スクリーンショット / Screenshots

![image](https://user-images.githubusercontent.com/34150349/119263632-d85bd280-bc1a-11eb-9aeb-e3635970dbe1.png)

![image](https://user-images.githubusercontent.com/34150349/119263653-ee699300-bc1a-11eb-856c-0d52bb6535a0.png)

![image](https://user-images.githubusercontent.com/34150349/119263735-37b9e280-bc1b-11eb-82b2-377257314064.png)

2021-05-23 14:42 UTC, HyodaKazuaki commented on assets/locales/en.json
> +  "注釈": "This is a provisional translation. Please be aware that there may be mistranslations.",
この部分ですが、翻訳対象の文字が`注釈`だと翻訳時に意味が伝わらない可能性が高いように感じます
* 有志によって翻訳されたもので正確でない可能性があること
* 誤った翻訳や追加の翻訳に協力してくれる場合は[Google スプレッドシート](https://docs.google.com/spreadsheets/d/19L-L-wVweHNe3avcKDyYWc3SkZswDpL9x4zM5kIyg58/edit?usp=sharing)で翻訳に参加してほしいこと
* 日本語でも同じような文面を表示すること
などを追加すると良さそうに感じます
@stshsn @nomunomu0504 意見を伺えますか？

2021-05-23 14:42 UTC, HyodaKazuaki reviewed
LGTMですが、意見を伺いたいと思います

2021-05-23 14:48 UTC, nomunomu0504 commented on assets/locales/en.json
> +  "注釈": "This is a provisional translation. Please be aware that there may be mistranslations.",
そもそも、この「注釈」ってどこで使われてます？
元々は「Comments」っていう翻訳だったので、急にこうなるのは一瞬不自然に感じたので...

2021-05-23 23:51 UTC, stshsn commented on assets/locales/en.json
> +  "注釈": "This is a provisional translation. Please be aware that there may be mistranslations.",
@nomunomu0504 
「注釈」に対応する部分が使われているのは、スクリーンショットの2つ目の部分です。
トップ画面のメインタイトル下に表示されるもので、日本語の場合は非表示になっていると思います。

2021-05-23 23:53 UTC, stshsn commented on assets/locales/en.json
> +  "注釈": "This is a provisional translation. Please be aware that there may be mistranslations.",
#1178 で報告され、#2289 で一度修正していますね。

2021-05-25 03:51 UTC, nomunomu0504 commented on assets/locales/en.json
> +  "注釈": "This is a provisional translation. Please be aware that there may be mistranslations.",
あれ。ということはどこかで戻ってしまったのか🤔

2021-05-25 03:52 UTC, nomunomu0504 commented on assets/locales/en.json
> +  "注釈": "This is a provisional translation. Please be aware that there may be mistranslations.",
その部分は英語訳のときのみの表示で問題ないと思います。

>誤った翻訳や追加の翻訳に協力してくれる場合はGoogle スプレッドシートで翻訳に参加してほしいこと
これは専用のpage or 既存のabout に追記載しておく方向にしましょうか。

@stshsn @HyodaKazuaki 
こちらでどうでしょうか。

2021-05-25 03:53 UTC, nomunomu0504 commented
実装方針としてはLGTMです！

2021-05-25 03:54 UTC, nomunomu0504 requested changes

2021-05-25 03:54 UTC, nomunomu0504 commented on assets/locales/en.json
> +  "「青：良好」／「黄：注意報」／「赤：警報」／「黒：緊急事態」": "Blue: Good / Yellow: Warning / Red: Alarm / Black: Emergency",
Alarm → Alert な気がします！

2021-05-25 04:01 UTC, stshsn commented on assets/locales/en.json
> +  "「青：良好」／「黄：注意報」／「赤：警報」／「黒：緊急事態」": "Blue: Good / Yellow: Warning / Red: Alarm / Black: Emergency",
確かに

2021-05-25 04:30 UTC, HyodaKazuaki commented on assets/locales/en.json
> +  "注釈": "This is a provisional translation. Please be aware that there may be mistranslations.",
@nomunomu0504 @stshsn 
`注釈`というワードがわかりづらいという問題はどうしますか？
案としては「これは仮訳です。誤訳の可能性がありますのでご注意ください。」(#2289で挿入された英文の日本語訳)か、「翻訳は完全ではありません」(#1178で提案されたもの)が挙げられます

2021-05-25 04:31 UTC, h-nomura0504 commented on assets/locales/en.json
> +  "注釈": "This is a provisional translation. Please be aware that there may be mistranslations.",
>注釈というワードがわかりづらいという問題

そもそも注釈って文言はWeb上には出ないんですよね？（英訳のときのみアセットが表示される）
分かりづらいというのは実装上で。という意味でしょうか。

2021-05-25 04:33 UTC, nomunomu0504 commented on assets/locales/en.json
> +  "注釈": "This is a provisional translation. Please be aware that there may be mistranslations.",
↑ アカウント間違えました。すいません...

2021-05-25 04:44 UTC, HyodaKazuaki commented on assets/locales/en.json
> +  "注釈": "This is a provisional translation. Please be aware that there may be mistranslations.",
> そもそも注釈って文言はWeb上には出ないんですよね？（英訳のときのみアセットが表示される）

コード上は存在していますが、Webページとして`注釈`が出てくることはありません

> 分かりづらいというのは実装上で。という意味でしょうか。

実装上(翻訳上)わかりづらいという意味です
翻訳を行うスプレッドシートでは日本語の正文と対応づける形で訳文が当てられるため、正文を見ただけでこれが仮訳であることを意味する文章であることがわかる状態じゃないと、翻訳に協力してもらう方が勘違いしてしまう可能性があります

2021-05-26 23:44 UTC, nomunomu0504 commented on assets/locales/en.json
> +  "注釈": "This is a provisional translation. Please be aware that there may be mistranslations.",
>実装上(翻訳上)わかりづらいという意味です
翻訳を行うスプレッドシートでは日本語の正文と対応づける形で訳文が当てられるため、正文を見ただけでこれが仮訳であることを意味する文章であることがわかる状態じゃないと、翻訳に協力してもらう方が勘違いしてしまう可能性があります

単純に「本サイトについて」とかではまずいですかね🤔、このサイトの状態や翻訳など全てを含めた意味にするような感じで...

2021-05-26 23:45 UTC, nomunomu0504 approved these changes

2021-05-27 03:46 UTC, merged